config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  get 'search/results'
  resources :search

  get 'static_pages/home'

  get 'static_pages/display'

  get 'static_pages/search'
  
  #search bar routes
  get 'static_pages/search', to: 'static_pages#search'
  post 'static_pages/display', to: 'static_pages#display'

  resources :reviews
  resources :orders
  resources :order_items
  resources :products do
    resources :reviews, except: [:show, :index]
  end
  get 'sessions/new'
  

  resources :users
  get 'main/contact'

  get 'main/display'

  get 'main/home'
  
  root 'main#home'
  
  get '/signup', to: 'users#new'
  
  get '/login', to: 'sessions#new'
  
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items, dependent: :destroy
    belongs_to :user
    
    def total
        order_items.map do |i| i.subtotal end.sum
    end
  
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
    
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @orders = Order.find(params[:id])
  end
  
  def empty
    @orders.each do |order|
      @order.destroy.all
    end
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params.merge(status: 'submitted'))
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to products_path, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :status)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :order_user_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :order_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user_id %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Order - Shopping Cart</h1>

<hr>

<table>
  <thead>
 <th>Customer</th>
    <th>Status:</th>
    <th>Items:</th>
  </thead>
  <tbody>
      <td><%= @order.user.name if @order.user %></td>
      <td><%= @order.status %></td>
      <td><%= @order.order_items.count %></td>
  </tbody>
</table>

<hr>

<table id= "products" style="margin-left: 30px; border-collapse: collapse;" border="0"; cellspacing="0";>
  <thead>
  <tr>
    <th>Image</th>
    <th>Product Name</th>
    <th>Color</th>
    <th>Size</th>
    <th>Quantity</th>
    <!-- th>Stock</th -->
    <th>Price</th>
    <th>Remove</th>
  </thead>
  
  <tbody style="border-left: 0px none; border-right: 0px none;">

   <% @order.order_items.each do | item | %>
    </tr>
      <td><%= image_tag "products/#{item.product.image_url}" %></td>
      <td> <%= item.product.title %></td>
      <td> <%= item.product.color %></td>
      <td> <%= item.product.size %></td>
      <td> <%= link_to item.quantity, edit_order_item_path(item) %></td>
      <!-- td><   print_stock(item.product.stock, item.quantity) %></td -->
      <td> <%= item.product.price %></td>
      <td><%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
  </tbody>
</table>

<hr>

<h4>SUBTOTAL</h4>

  <% @order.order_items.each do | item | %>
  <%= print_price item.subtotal %>
  <% end %>
  <p>EXCLUDING TAX & SHIPPING</p>


  <h4>Order Total:</h4>
 <%= print_price @order.total %>
 
<hr>

<%= link_to "Empty Cart", @order, data: { confirm: 'Are you sure?' }, method: :delete %>  |

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', products_path %>