config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  get 'search/results'
  resources :search

  get 'static_pages/home'

  get 'static_pages/display'

  get 'static_pages/search'
  
  #search bar routes
  get 'static_pages/search', to: 'static_pages#search'
  post 'static_pages/display', to: 'static_pages#display'

  resources :reviews
  resources :orders
  resources :order_items
  resources :products do
    resources :reviews, except: [:show, :index]
  end
  get 'sessions/new'
  

  resources :users
  get 'main/contact'

  get 'main/display'

  get 'main/home'
  
  root 'main#home'
  
  get '/signup', to: 'users#new'
  
  get '/login', to: 'sessions#new'
  
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    validates_numericality_of :price
    validates :stock, numericality: {greater_than_or_equal_to: 0}
    has_many :order_items
    accepts_nested_attributes_for :order_items
    
    has_many :reviews

    
    def self.search(search)
        where("title Like ?", "%#{search}%")
        where("color Like ?", "%#{search}%")
        where("size Like ?", "%#{search}%")
    end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  # GET /products
  # GET /products.json
  def index
    @users = User.all
     @products = Product.all
    
    
  end

  # GET /products/1
  # GET /products/1.json
  def show
  #  @products = Product.find(params[:product_id])
    @reviews = Review.where(product_id: @product.id)
    @products = Product.all
    if @reviews.blank?
      @avg_rating = 0
    else
    @avg_rating = @reviews.average(:rating).round(2)
   end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :price, :color, :size, :description, :image_url, :stock)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
    def print_price(price)
        number_to_currency price
    end
    
    def price=(input)
      input.delete!("$")
      super
    end
    
    def print_stock(stock, requested = 1)
        if stock > requested
            content_tag :span, class: "in_stock" do
                #{stock}
            end
        elsif stock < 0
            content_tag :span, class: "out_of_stock" do
                "out of stock"
            end
        elsif stock > 0 && stock < requested
            content_tag(:span, "Insufficient stock", class: "low_stock") do
                #{stock}
            end
        end
    end
end

app/views/products/_form.html.erb
<%= form_with(model: @product, local: true) do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title %>
  </div>

  <div class="field">
    <%= form.label :price, "Price (like 29.99)" %>
    <%= form.text_field :price, id: :product_price %>
  </div>
  
  <div class="field">
    <%= form.label :stock %>
    <%= form.text_area :stock, id: :product_stock %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :product_color %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size, id: :product_size %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :image_url, "Image_URL" %>
    <%= form.text_field :image_url, id: :product_image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Women's Clothing</h1>

<div class="row">
<% @products.each do |product| %>
<div class="col-md-3">
  <%= image_tag "products/#{product.image_url}" %>
  <%= link_to product.title, product %>
  <%= print_price(product.price) %>
</div>
<% end %>
</div>


<table id= "products" style="margin-left: 30px; border-collapse: collapse;" border="0"; cellspacing="0";>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <!-- th>Stock</th --> 
      <th>Color</th>
      <th>Size</th>
      <th>Description</th>
      <th>Image </th>
      <th>Buy</th>
      <th>View</th>
      <!-- th colspan="4"></th -->
    </tr>
  </thead>

  <tbody style="border-left: 0px none; border-right: 0px none;">
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.title, product %></td>
        <td><%= print_price(product.price) %></td>
        <!-- td>< print_stock(product.stock) %></td --> 
        <td><%= product.color %></td>
        <td><%= product.size %></td>
        <td><%= product.description %></td>
        <td><%= image_tag "products/#{product.image_url}" %></td>
        <td><%= button_to "Add to Cart", order_items_path(product_id: product.id) %></td>
        <td><%= link_to 'Show', product %></td>
        
        <% if current_user.admin? %>
  
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>
<br>
<br>


<%= link_to 'Create a New Product', new_product_path, id: "new-product" %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/results.html.erb
 <% if !@res || @res.total == 0 %>
     <span>No results.</span>
     <% else %>
     <span>Found <%= "#{@res.total}" %> results.</span>
     <table>
<thead> <tr>
           <th>Name</th>
           <th>Description</th>
           <th>Price</th>
           <th></th>
         </tr>
       </thead>
       <tbody>
         <% @res.results.each do |product| %>
           <tr>
             <td><%= product.name %></td>
             <td><%= product.description %></td>
             <td><%= product.price %></td>
             <td><%= link_to 'Show', product %></td>
           </tr>
         <% end %>
       </tbody>
     </table>
<% end %>

app/views/products/show.html.erb
<script src="//code.jquery.com/jquery-3.1.0.slim.min.js"></script>

<script src="lightzoom.js">
  $('.image-selector').lightzoom(
    glassSize   : 175
    zoomPower   : 3

);
</script>



<div class="row">
<div class="col-md-8">
  
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @product.image_url %>
</p>
  
<!-- p>
  < image_tag @product.image_url, :size => '150x150' %>
</p -->
    
</div>

<div class="col-md-4">

<h2>
  <strong><%= @product.title %></strong>
</h2>


<div class="star-rating" data-score= <%= @avg_rating %> ></div>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Color:</strong>
  <%= @product.color %>
</p>

<p>
  <strong>Size:</strong>
  <%= @product.size %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>


<br>
<br>

<%= button_to "Add to Cart", order_items_path(@product_id) %>

<br>

<%= link_to "Write a Review", new_product_review_path(@product), class: "btn btn-primary" %>

</div>
</div>

<hr>

<h3 style="text-align: center;">COMPLETE YOUR LOOK</h3>
<div class="center">
<% @products.each do |p| %>
    <%= image_tag "products/#{@product.image_url}" %>
<% end %>
</div>


<hr>
<h3>REVIEWS</h3>
<% if @reviews.blank? %>
<h3>No reviews yet. Be the first to write one!</h3>
<% else %>
  <% @reviews.each do |review| %>
  <p><strong>Rating: </strong><%=  review.rating %></p>
  <div class="star-rating" data-score= <%= review.rating %>> </div>
  <p><strong>Comment: </strong><%= review.comment %></p>
  <hr>
<% end %>
<% end %>


<br>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>


<script>
  $('.star-rating').raty(
    {path: 'images/ratings',
    readOnly: true,
      score: function(){
        return $(this).attr('data-score');
      }
    });
</script>