config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  get 'search/results'
  resources :search

  get 'static_pages/home'

  get 'static_pages/display'

  get 'static_pages/search'
  
  #search bar routes
  get 'static_pages/search', to: 'static_pages#search'
  post 'static_pages/display', to: 'static_pages#display'

  resources :reviews
  resources :orders
  resources :order_items
  resources :products do
    resources :reviews, except: [:show, :index]
  end
  get 'sessions/new'
  

  resources :users
  get 'main/contact'

  get 'main/display'

  get 'main/home'
  
  root 'main#home'
  
  get '/signup', to: 'users#new'
  
  get '/login', to: 'sessions#new'
  
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imo Clothing: <%= controller.action_name %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
        <div class="headliner">
        <p><strong>
              Use Promo Code: 15OFF for 15% off your next purchase.
          </strong>
        </p>
        </div>
      </header>
    
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-success">
        <%= message %>
        </div>
      <% end %>
      <% flash.clear %>
  </div>

    <div class="container1">
      <nav>
        <%= image_tag "Imo Clothing.jpg" %>
        <ul class="nav navbar-nav navbar-right">
          <!-- li>
       < render :template => "search/index" %>
        </li -->
           <li><%= link_to image_tag "SeachBar.jpg", controller: '#', action: '#', :size => '20x20' %></li>
       <div class="searchBar">
          <%= form_tag(controller: "static_pages", action: "display", :method => "post", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Clothing by color, type or size", class: "text_f form-control" %>
          <!-- <%= submit_tag "Search", class: "btn btn-primary" %> -->
         <% end %>
      </div>
          <li><%= link_to "Home", controller: "main", action: "home" %></li>
          <li><%= link_to "Contact", controller: "main", action: "contact" %></li>
          <li><%= link_to "Cart", orders_path %></li>
        <% if logged_in? %>
          
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Users", users_path if current_user.admin? %></li>
        <!--  <li>< link_to "Add Product", controller: "products", action: "new" if current_user.admin? %></li> -->
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
               <li><%= link_to "Log out", logout_path, method: :delete %></li>
        </ul>
          <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
    

    
    <div class="container">
      <%= yield %>
    </div>
      
<br>
<br>
<br>
<br>
      <footer class="footer">
        <nav>
          <ul>
            <div class="left">
            <li><%= link_to "About", controller: "main", action: "display" %></li>
            <li><%= link_to "Contact", controller: "main", action: "contact" %></li>
            </div>
            <div class="right">
            <li><%= link_to "Facebook", "http://www.facebook.com" %></li>
            <li><%= link_to "Twitter", "http://www.twitter.com" %></li>
            <li><%= link_to "Instagram", "http://www.instagram.com" %></li>
            <li>&copy 2018 by Grace Saint</li>
            </div>
          </ul>
        </nav>
      </footer>
  </body>
</html>